# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-09 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureMail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='btrf',
            field=models.CharField(default=b'Betreff', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.CharField(default=b'test@mail.de', max_length=255),
        ),
    ]
